(* open Battle_event *)
(* open Config *)
(* open! Postgresql *)

(* (1* let create_connection conninfo = *1) *)
(* (1*   try Some (new connection ~conninfo ()) with *1) *)
(* (1*   | Error e -> *1) *)
(* (1*       prerr_endline (string_of_error e) ; *1) *)
(* (1*       None *1) *)
(* (1*   | _ -> None *1) *)

(* let create_postgresql_persister config = *)
(*   match create_connection config.postgres_conn_string with *)
(*   | None -> fun _ -> None *)
(*   | Some c -> ( *)
(*       fun battle_event -> *)
(*         try *)
(*           let query = Printf.sprintf "INSERT INTO id VALUES('%s')" (c#escape_string battle_event.id) in *)
(*           let res = c#exec query in *)
(*           match res#status with *)
(*           | Command_ok -> print_endline "Insert successful" ; Some battle_event *)
(*           | _ -> print_endline "Insert failed" ; Some battle_event *)
(*         with Error _ -> print_endline c#error_message ; Some battle_event ) *)
