name: OCaml CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup OCaml
      uses: avsm/setup-ocaml@v2
      with:
        ocaml-compiler: '4.14.0'

    - name: Check
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config zlib1g-dev libpq-dev librdkafka-dev 
        opam install . --deps-only --with-test --with-doc
        opam install dune
        eval $(opam env)
        make lint
        make test
        make
